# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OBilet-Project' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'Alamofire', '5.0.0-rc.2'
  pod 'AlamofireObjectMapper', '6.2.0'
  pod 'ObjectMapper'

  use_frameworks!

  # Pods for OBilet-Project

end
